version: "3"

services:
  api:
    image: terraformize
    ports:
      - '80:80'
    restart: always
    environment:
      AUTH_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGkiOiJ0ZXJyYWZvcm1pemUifQ.KzUGr_Ym7gVKKe3VQNb1liF1JkScfBYyc5zimdG3eJY
      #BASIC_AUTH_USER: leonardo
      #BASIC_AUTH_PASSWORD: 081264
      #AWS_ACCESS_KEY_ID: 
      #AWS_SECRET_ACCESS_KEY: 
      #AWS_DEFAULT_REGION: us-east-1
